In [3]:
#mean removal
import numpy as np
from sklearn import preprocessing
data=np.array([[2],[4],[6],[8],[10]])
mean=data.mean(axis=0)
mean_remove=data-mean
print(mean_remove)
print(mean_remove.std(axis=0))
print(mean_remove.mean(axis=0))
data_standerdize=preprocessing.scale(data)

[[-4.]
 [-2.]
 [ 0.]
 [ 2.]
 [ 4.]]
[2.82842712]
[0.]


In [5]:
#scalling
import numpy as np
from sklearn import preprocessing
data=np.array([[10],[20],[30],[40],[50]])
print(data)
data_scaler=preprocessing.MinMaxScaler(feature_range=(0,1))
scaled_data=data_scaler.fit_transform(data)
print(scaled_data)

[[10]
 [20]
 [30]
 [40]
 [50]]
[[0.  ]
 [0.25]
 [0.5 ]
 [0.75]
 [1.  ]]


In [8]:
#Normalization
import numpy as np
from sklearn import preprocessing
data=np.array([[3,4],[1,2],[5,12]])
print(data)
print("*"*70)

normalizaed_l1=preprocessing.normalize(data,norm="l1")
print(normalizaed_l1)
print("*"*70)
normalizaed_l2=preprocessing.normalize(data,norm="l2")
print(normalizaed_l2)


[[ 3  4]
 [ 1  2]
 [ 5 12]]
**********************************************************************
[[0.42857143 0.57142857]
 [0.33333333 0.66666667]
 [0.29411765 0.70588235]]
**********************************************************************
[[0.6        0.8       ]
 [0.4472136  0.89442719]
 [0.38461538 0.92307692]]


In [9]:
#Binarization
import numpy as np
from sklearn import preprocessing
data=np.array([[10.2],[22.5],[30],[14.22],[50]])
print(data)
print("*"*70)
binarazed_data=preprocessing.Binarizer(threshold=20).transform(data)
print(binarazed_data)

[[10.2 ]
 [22.5 ]
 [30.  ]
 [14.22]
 [50.  ]]
**********************************************************************
[[0.]
 [1.]
 [1.]
 [0.]
 [1.]]


In [19]:
#Label Encoding
import numpy as np
from sklearn import preprocessing

labels=['apple','banana','mango','grapes','mango','banana']
print("Labels:",labels)

lebels_encoder=preprocessing.LabelEncoder()
op=lebels_encoder.fit_transform(labels)
print(op)

test_labels=['mango','apple']
print(test_labels,lebels_encoder.transform(test_labels))
test_codes=[1,3]
print(lebels_encoder.inverse_transform(test_codes))

Labels: ['apple', 'banana', 'mango', 'grapes', 'mango', 'banana']
[0 1 3 2 3 1]
['mango', 'apple'] [3 0]
['banana' 'mango']


In [22]:
#Regrassion
#Linear regrassion

import numpy as np
from sklearn.linear_model import LinearRegression

exper=np.array([[1],[2],[3],[4],[5]])
salary=np.array([[30000],[35000],[40000],[45000],[50000]])

model=LinearRegression()
model.fit(exper,salary)

predicated_salary=model.predict([[6]])
print(predicated_salary)

[[55000.]]


In [24]:
#Decision tree

import numpy as np
from sklearn.tree import DecisionTreeRegressor

exper=np.array([[1],[2],[3],[4],[5]])
salary=np.array([[30000],[35000],[40000],[45000],[50000]])

model=DecisionTreeRegressor(max_depth=2)
model.fit(exper,salary)

print(model.predict([[6]]))

[47500.]
